name: SimpleHTTPServer
load: STARTUP
main: org.primesoft.simplehttpserver.SimpleHTTPServerMain
version: 0.1
website: 
description: A plugin that allows you to run a small HTTP server directly from Spigot
authors: [SBPrime]
depend: []
softdepend: []
permissions:
  SServer.*:
    description: Grants access to all plugin commands permissions
    default: op
    children:
      RCUtils.CommandBlock.*: true
      RCUtils.Reload: true
  SServer.Reload:
    description: Grants access to reload configuration command
    default: op
